### ISSUE TITLE
Example does not run

### ISSUE THREAD

**Issue by thdave** [skellyb/fluxstream#1]
Hi

Im trying to get your example to run , but I get a couple of errors 
1. isOn is null , you have to set isOn to false using 

var Light = React.createClass({

```
getInitialState:function(){
    return {

        isOn: false
    }
},
```

   ...................
});
1. I get the error Uncaught TypeError: Cannot read property 'streams' of undefined , even if I set the Light stroe props t0 {this.store} , 

Can you tell me what I am missing ?

**Comment by thdave** [comment]
My error using your example incorrectly.

**Comment by skellyb** [comment]
Let me know if you have any other questions.
